[general]
live_config_reload = true
import = [
  "~/.config/alacritty/themes/ayu_dark.toml",
  "~/.config/macos/alacritty/alacritty.macos.toml",
  "~/.config/linux/alacritty/alacritty.linux.toml",
]

[cursor]
style = { shape = "Beam" }
vi_mode_style = { shape = "Block" }

[window]
startup_mode = "Maximized"
decorations = "none"
option_as_alt = "Both"
opacity = 0.9
blur = false
