# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/Configuring/Variables/#input

input {
    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 0
}

device {
  name = at-translated-set-2-keyboard
  kb_layout = de
}

device {
  name = ferris-bling-lp-keyboard
  kb_layout = us
}

device {
  name = hoksi-technology-durgod-taurus-k320
  kb_layout = gb
}
