#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_service_mode_enabled_changed

default=(
  background.color="0x00000000"
  label.font="helvetica"
  label.font.size="12.0"
  label.color="0xffffffff"
  icon.padding_right="8"
)
sketchybar --default "${default[@]}"

# Workspaces
workspaces=( $(aerospace list-workspaces --all) )
for workspace_id in ${workspaces[@]}; do
  FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)

  sketchybar --add item  workspaces."$workspace_id" left \
              --subscribe workspaces."$workspace_id" aerospace_workspace_change \
              --set       workspaces."$workspace_id" \
                          background.drawing=off \
                          click_script="aerospace workspace $workspace_id" \
                          label.font="Hack Nerd Font" \
                          label.font.size="12.0" \
                          label.width="16" \
                          script="$PLUGIN_DIR/aerospace $workspace_id"
done

# Clock
sketchybar --add item clock right \
           --set      clock \
                      background.drawing=off \
                      label.color="0xffffffff" \
                      update_freq=10 \
                      script="$PLUGIN_DIR/clock"

# Spacer
sketchybar --add item spacer right \
           --set      spacer \
                      label.width="32" \
                      update_freq=10

# Battery
sketchybar --add item battery right \
           --set      battery \
                      label.font="Apple Color Emoji" \
                      label.font.size="8" \
                      label.color="0xffffffff" \
                      icon.font="Apple Color Emoji" \
                      icon.font.size="8" \
                      update_freq=10 \
                      script="$PLUGIN_DIR/battery"

# Spacer
sketchybar --add item spacer2 right \
           --set      spacer2 \
                      label.width="32"\
                      update_freq=10

# Weather
sketchybar --add item weather right \
           --set      weather \
                      label.font="helvetica" \
                      label.font.size="12.0" \
                      label.color="0xffffffff" \
                      icon.font="Apple Color Emoji" \
                      update_freq=10 \
                      script="$PLUGIN_DIR/weather"

sketchybar --hotload on
sketchybar --update
sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)

