[notebook]
dir = "/home/mat/notes"

[format.markdown]
link-format = "markdown"
hashtags = true
colon-tags = false
multiword-tags = false

[tool]
editor = "nvim"
fzf-preview = "bat -p --color always {-1}"

[lsp.diagnostics]
dead-link = "error"

[note]
filename = "{{id}}_{{slug title}}"
template = "default.md"

[group.daily]
paths = ["dailies"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
template = "daily.md"

[group.ticket]
paths = ["tickets"]

[group.ticket.note]
filename = "{{extra.ticket_number}}_{{slug title}}"
template = "ticket.md"

[alias]
today = 'zk new --no-input "$ZK_NOTEBOOK_DIR/dailies"'
note = 'zk new --title "$(printf "Title: " >&2 && read t && printf "%s" "$t")"'
l = 'zk edit -i --tag "NOT daily" --tag "NOT ticket"'
ls = 'zk edit -i --tag "NOT daily" --tag "NOT ticket"'
notes = 'zk edit -i --tag "NOT daily" --tag "NOT ticket"'
tickets = "zk edit -i --tag ticket"
d = "zk edit -i --tag daily --sort created-"
dailies = "zk edit -i --tag daily --sort created-"
