[notebook]
dir = "/home/mat/notes/"

[format.markdown]
link-format = "markdown"
hashtags = true
colon-tags = false
multiword-tags = false

[tool]
editor = "nvim"
fzf-preview = "bat -p --color always {-1}"

[lsp.diagnostics]
dead-link = "error"

[note]
template = "default.md"

[group.daily]
paths = ["daily"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
template = "daily.md"

[alias]
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/daily"'
# log = 'zk new --no-input "$ZK_NOTEBOOK_DIR/daily"'
today = 'zk new --no-input "$ZK_NOTEBOOK_DIR/daily"'
l = "zk edit -i"
# t = "zk tag"
# a = "zk new --title=$1"
# add = "zk new --title=$1"
n = 'zk new --title "$(printf "Title: " && read t && printf "%s" "$t")"'
new = 'zk new --title "$(printf "Title: " && read t && printf "%s" "$t")"'
# q = "zk edit --tag quick-note"
# quick = "zk edit --tag quick-note"
conf = '$EDITOR "$ZK_NOTEBOOK_DIR/.zk/config.toml"'
