local utils = require("utils")

utils.map("v", "<", "<gv", utils.map_opts)
utils.map("v", ">", ">gv", utils.map_opts)
utils.map({ "n", "v" }, "c", '"_c', utils.map_opts)
utils.map({ "n", "v" }, "C", '"_C', utils.map_opts)
utils.map("v", "p", "P", utils.map_opts)
utils.map({ "n", "v", "i" }, "<c-down>", ":NavigatorDown<CR>", utils.map_opts)
utils.map({ "n", "v", "i" }, "<c-up>", ":NavigatorUp<CR>", utils.map_opts)
utils.map({ "n", "v", "i" }, "<c-right>", ":NavigatorRight<CR>", utils.map_opts)
utils.map({ "n", "v", "i" }, "<c-left>", ":NavigatorLeft<CR>", utils.map_opts)
utils.map("n", "<leader>bo", ":%bd|e#|bd#<CR>", utils.map_opts) -- close all buffers but the current one
utils.map({ "n", "v", "i" }, "<C-x>", ":bd<CR>", utils.map_opts)
utils.map("n", "<leader>by", ":%y<CR>", utils.map_opts)
utils.map("n", "<leader>bY", ":let @+ = expand('%:p')", utils.map_opts)
utils.map("n", "<C-u>", "<C-u>zz")
utils.map("n", "<C-d>", "<C-d>zz")
utils.map("n", "<Down>", "gj", utils.map_opts)
utils.map("n", "<Up>", "gk", utils.map_opts)
utils.map("n", "<Esc>", ":noh<CR>", utils.map_opts)
utils.map("t", "<Esc>", "<C-\\><C-n>", utils.map_opts)
-- utils.map("n", "<Tab>", ":b#<CR>", utils.map_opts)
utils.map("n", "<leader>e", ":Oil<CR>", utils.map_opts)
utils.map("n", "<leader>s", ":SupermavenToggle<CR>:redrawstatus<CR>", utils.map_opts)
utils.map("n", "<leader><leader>", ":JABSOpen<CR>", utils.map_opts)
utils.map("n", "<leader>c", function()
  if vim.bo.buftype == "quickfix" then
    vim.cmd("cclose")
  else
    vim.cmd("copen")
  end
end, utils.map_opts)
utils.map({ "n", "x", "o" }, "s", function()
  require("flash").jump()
end, { desc = "Flash" })

utils.map("n", "<leader>sf", require("fzf-lua").files, utils.map_opts)
utils.map("n", "<leader>sw", require("fzf-lua").grep_cword, utils.map_opts)
utils.map("n", "<leader>sr", require("fzf-lua").oldfiles, utils.map_opts)
utils.map("n", "<leader>st", require("fzf-lua").live_grep, utils.map_opts)
utils.map("n", "<leader>sh", require("fzf-lua").helptags, utils.map_opts)
utils.map("n", "<leader>sd", require("fzf-lua").lsp_document_diagnostics, utils.map_opts)
utils.map({ "n", "v" }, "<leader>sa", ":GpChatFinder<CR>", utils.map_opts)
utils.map("n", "<leader><leader>", require("fzf-lua").buffers, utils.map_opts)

utils.map("n", "gd", vim.lsp.buf.definition, utils.map_opts)
utils.map("n", "K", vim.lsp.buf.hover, utils.map_opts)
utils.map("n", "gr", vim.lsp.buf.references, utils.map_opts)
utils.map("n", "<leader>lr", vim.lsp.buf.rename, utils.map_opts)
utils.map("n", "gl", vim.diagnostic.setqflist, utils.map_opts)
utils.map({ "n", "i" }, "<S-Down>", function()
  vim.diagnostic.jump({ count = 1, float = true })
end, utils.map_opts)
utils.map({ "n", "i" }, "<S-Up>", function()
  vim.diagnostic.jump({ count = -1, float = true })
end, utils.map_opts)

-- ai stuff
utils.map({ "n", "v" }, "<leader>aa", ":GpRewrite<CR>", utils.map_opts)
utils.map({ "n", "v" }, "<leader>ac", ":GpChatToggle<CR>", utils.map_opts)
utils.map({ "n", "v" }, "<leader>an", ":GpChatNew<CR>", utils.map_opts)
utils.map({ "n", "v" }, "<leader>ad", ":GpChatDelete<CR>", utils.map_opts)
utils.map({ "n", "v" }, "<leader>af", ":GpChatFinder<CR>", utils.map_opts)

-- buffers
utils.map("n", "<tab>", ":bnext<CR>", utils.map_opts)
utils.map("n", "<S-tab>", ":bprevious<CR>", utils.map_opts)

-- neo-tree buffers
utils.map("n", "<leader><leader>", require("fzf-lua").buffers, utils.map_opts)
