local core = require("core")

core.map_key("v", "<", "<gv")
core.map_key("v", ">", ">gv")
core.map_key({ "n", "v" }, "c", '"_c')
core.map_key({ "n", "v" }, "C", '"_C')
core.map_key("v", "p", "P")
core.map_key({ "n", "v", "i" }, "<c-down>", ":NavigatorDown<CR>")
core.map_key({ "n", "v", "i" }, "<c-up>", ":NavigatorUp<CR>")
core.map_key({ "n", "v", "i" }, "<c-right>", ":NavigatorRight<CR>")
core.map_key({ "n", "v", "i" }, "<c-left>", ":NavigatorLeft<CR>")
core.map_key("n", "<leader>bo", ":%bd|e#|bd#<CR>") -- close all buffers but the current one
core.map_key({ "n", "v", "i" }, "<C-x>", ":bd<CR>")
core.map_key("n", "<leader>by", ":let @+ = expand('%:p')")
core.map_key("n", "Y", "y$", { desc = "Yank to end of line" })
core.map_key("n", "<C-u>", "<C-u>zz")
core.map_key("n", "<C-d>", "<C-d>zz")
core.map_key("n", "<Down>", "gj")
core.map_key("n", "<Up>", "gk")
core.map_key("n", "<Esc>", ":noh<CR>")
core.map_key("t", "<Esc>", "<C-\\><C-n>")
core.map_key("n", "<Tab>", ":b#<CR>")
core.map_key("n", "<leader>e", ":Neotree toggle=true source=filesystem<CR>")
core.map_key("n", "<leader>s", ":SupermavenToggle<CR>:redrawstatus<CR>")
core.map_key("n", "<leader>f", function()
  vim.b.disable_autoformat = not vim.b.disable_autoformat
  vim.cmd("redrawstatus")
end)
core.map_key("n", "<leader>c", function()
  if vim.bo.buftype == "quickfix" then
    vim.cmd("cclose")
  else
    vim.cmd("copen")
  end
end)
core.map_key("n", "<leader>a", function()
  require("nvim-autopairs").toggle()
end, { desc = "Toggle autopairs" })
core.map_key({ "n", "x", "o" }, "s", function()
  require("flash").jump()
end, { desc = "Flash" })

core.map_key("n", "<leader>sf", require("fzf-lua").files)
core.map_key("n", "<leader>sw", require("fzf-lua").grep_cword)
core.map_key("n", "<leader>sr", require("fzf-lua").oldfiles)
core.map_key("n", "<leader>st", require("fzf-lua").live_grep)
core.map_key("n", "<leader>sh", require("fzf-lua").helptags)
core.map_key("n", "<leader>sd", require("fzf-lua").lsp_document_diagnostics)
core.map_key("n", "<leader>sm", require("fzf-lua").marks)
core.map_key("n", "<leader>sn", ":ZkNotes<CR>")
core.map_key("n", "<leader><leader>", require("fzf-lua").buffers)

core.map_key("n", "gd", vim.lsp.buf.definition)
core.map_key("n", "K", vim.lsp.buf.hover)
core.map_key("n", "gr", vim.lsp.buf.references)
core.map_key("n", "<leader>lr", vim.lsp.buf.rename)
core.map_key("n", "<leader>ls", ":Neotree toggle=true source=document_symbols<CR>")
core.map_key("n", "<leader>ll", vim.diagnostic.setqflist)
core.map_key("n", "<leader>gl", ":Gitsigns setqflist<CR>")
core.map_key("n", "<leader>gr", ":Gitsigns reset_hunk<CR>")
core.map_key({ "n", "i" }, "<S-Down>", ":cn<CR>")
core.map_key({ "n", "i" }, "<S-Up>", ":cp<CR>")
core.map_key({ "n", "v" }, "<leader>aa", ":GpRewrite<CR>")
core.map_key({ "n", "v" }, "<leader>ac", ":GpChatToggle<CR>")
core.map_key({ "n", "v" }, "<leader>an", ":GpChatNew<CR>")
core.map_key({ "n", "v" }, "<leader>ad", ":GpChatDelete<CR>")
core.map_key({ "n", "v" }, "<leader>af", ":GpChatFinder<CR>")
