#!/usr/bin/env bash

if [ "$SENDER" = "aerospace_workspace_change" ]; then
  if [ "$1" = "$FOCUSED_WORKSPACE" ]; then
    sketchybar --set $NAME label.string=""
  else
    sketchybar --set $NAME label.string=""
  fi
fi
