#!/usr/bin/env bash

BATT_PERCENT=$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)
CHARGING=$(pmset -g batt | grep 'AC Power')

green="0xff009900"
yellow="0xffffff00"
orange="0xffff9900"
red="0xffff0000"

case ${BATT_PERCENT} in
    100) COLOR="$green" ;;
    9[0-9]) COLOR="$green" ;;
    8[0-9]) COLOR="$green" ;;
    7[0-9]) COLOR="$yellow" ;;
    6[0-9]) COLOR="$yellow" ;;
    5[0-9]) COLOR="$yellow" ;;
    4[0-9]) COLOR="$orange" ;;
    3[0-9]) COLOR="$orange" ;;
    2[0-9]) COLOR="$red" ;;
    1[0-9]) COLOR="$red" ;;
    *) COLOR="$red" ;;
esac
if [[ ${CHARGING} != "" ]]; then
  icon="⚡"
else
  icon="🔋"
fi

sketchybar --set "${NAME}" icon="${icon}" label="${BATT_PERCENT}%" label.color="${COLOR}"
