#!/usr/bin/env bash

BATT_PERCENT=$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)
CHARGING=$(pmset -g batt | grep 'AC Power')

green="0xff009900"
yellow="0xffffff00"
orange="0xffff9900"
red="0xffff0000"

case ${BATT_PERCENT} in
    100) label="🟥🟥🟧🟧🟧🟨🟨🟨🟩🟩" COLOR="$green" ;;
    9[0-9]) label="🟥🟥🟧🟧🟧🟨🟨🟨🟩🟩" ;;
    8[0-9]) label="🟥🟥🟧🟧🟧🟨🟨🟨🟩" ;;
    7[0-9]) label="🟥🟥🟧🟧🟧🟨🟨🟨" ;;
    6[0-9]) label="🟥🟥🟧🟧🟧🟨🟨" ;;
    5[0-9]) label="🟥🟥🟧🟧🟧🟨" ;;
    4[0-9]) label="🟥🟥🟧🟧🟧" ;;
    3[0-9]) label="🟥🟥🟧🟧" ;;
    2[0-9]) label="🟥🟥🟧" ;;
    1[0-9]) label="🟥🟥" ;;
    *) label="🟥" ;;
esac
if [[ ${CHARGING} != "" ]]; then
  icon="🔌"
else
  icon=""
fi

sketchybar --set "${NAME}" icon="${icon}" label="${label}"
